### ISSUE TITLE
Package global

### ISSUE THREAD

**Issue by dvc94ch** [jspm-meteor/discussion#1]
@guybedford What are your thought on that?

**Comment by guybedford** [comment]
It may be worth taking a small code example and attempting to work out what static transformations should be applied to make it work correctly in jspm.

The package global itself can then be shimmed in the correct way as part of such a transformation.

For JavaScript code analysis, Esprima or Acorn (used by Babel) should work well here.

**Comment by dvc94ch** [comment]
Do those help me with modifying the source maps? I need to offset all line counts after I make the transformations. How do source maps work with jspm?

**Comment by dvc94ch** [comment]
Ah I this has nothing to do with jspm, this has to do with dev tools. So what I need to do is modify the file in the source map to point to `jspm_packages/ml/json@1.0.3/...` instead of `packages/json.js`...

**Comment by guybedford** [comment]
Yes these techniques can be done in a way that respects source maps. Source maps work best with relative URLs so they don't have any absolute references in them.

file.js
```javascript
// ... code ...
//# sourceMappingURL=file.js.map
```
file.js.map contains source map with sources referenced relative as well to the folder the file is in.

**Comment by dvc94ch** [comment]
Since the systemjs loader compiles the es6 module there must be some support after all for source maps. So just adding the correct comment at the end of the module is all I have to do on the jspm/systemjs side?
Meteor uses absolute paths in their source maps like `/packages/json.js.map`, but it's a small thing to make them relative.

**Comment by guybedford** [comment]
Source maps support for input sources won't pick up the comment currently
actually.

It would do if we used CommonJS here instead of ES6, but then the final
bundle process won't concatenate the source maps either. Those two cases
should be marked as issues for SystemJS and SystemJS builder though.

**Comment by dvc94ch** [comment]
Then I'll let the source maps be for now. Do you want me to open them?

**Comment by guybedford** [comment]
It makes sense to open this when we get there.
