### ISSUE TITLE
basic systemjs loader

### ISSUE THREAD

**Issue by dvc94ch** [jspm-meteor/discussion#2]
I'm trying to get systemjs to execute the translate hook like this: Is this the right approach? The existing plugins to systemjs I'm looking at only handle static assets...
```javascript
JSON = undefined;
System.import('ml:json!mb').then(function() {
  if (typeof JSON === 'undefined') {
    setTimeout(function() {
      throw "JSON is undefined";
     });
  }
}).catch(function(err) {
  setTimeout(function() {
    throw err;
  });
});
```
ml stands for meteor-local and mb for meteor-binary (precompiled)

**Comment by guybedford** [comment]
Rather than treating this as a language to be transpiled, I'd suggest statically transforming the code within the build hook of the endpoint rather.

**Comment by dvc94ch** [comment]
Can you explain when the build hook gets called? When running install? The docs aren't clear on that, and my build hook in [https://github.com/jspm-meteor/jspm-meteor-local/blob/master/meteor-local.js#L101](https://github.com/jspm-meteor/jspm-meteor-local/blob/master/meteor-local.js#L101) doesn't seem to get called.

**Comment by guybedford** [comment]
Build gets called after download. Are you sure it's not being called?

**Comment by dvc94ch** [comment]
Yes, I'm rejecting the promise, that should certainly cause a reaction... What happens if the package is already cached? Do I have to delete it in the .jspm folder?

**Comment by guybedford** [comment]
Yes the cache implementation will skip the download and build hooks. You need to run `jspm install` with the `-f` flag to force skip the cache. The download folder will always be empty when the download hook is called.

**Comment by dvc94ch** [comment]
Ok that fixed, I'll reply on the other issues, I still need some time to wrap my head around them...
