### ISSUE TITLE
Handling dependencies

### ISSUE THREAD

**Issue by dvc94ch** [jspm-meteor/discussion#6]
I need to have the `isopack.json` and `web.browser.json` of all dependencies during the build. Otherwise I don't know what `packageVariables` they export.

**Comment by dvc94ch** [comment]
How does one go about `weak` and `unordered` dependencies?
`unordered` is meant to resolve circular references. I think systemjs already handles this. So can it be safely ignored?
As to `weak` dependencies those are for optional dependencies, so the important thing is that the weak  dependency calls `extendPackage()` first. On the other hand not handling `weak` dependencies won't break anything, it will just mean that the `weak` dependency won't be available when the package initializes. As long as we see a way forward on this one, this can be put off for a pretty long time.

**Comment by dvc94ch** [comment]
So I put some thought into this. When loading from github or atmosphere I have access to the `package.js` in the `getPackageConfig()` hook. I could start work on loading the `package.js` from github and then add the exports and implies to `pjson`. All I need then is a way to access the dependencies `pjson` from the `build` hook.

**Comment by dvc94ch** [comment]
Thinking about these problems:
To resolve imports I'm going to prefetch dependencies into the `.meteor` folder and use that as a plugin cache. When jspm requests a download I can then first check if it's already in the `.meteor` folder.
The problem with this solution is that I'll have to determine the package version jspm will pick in advance. If I pick the wrong version it could lead to trouble...
`weak` dependencies can be handled by using `System.import` instead of `import`.

**Comment by guybedford** [comment]
@dvc94ch I'd strongly advise making sure everything you do fits into the model of a package being a single folder and jspm configuration for jspm. And packages not needing to know anything about other packages during build time.

Do we really have to break this model specifically in these cases?

**Comment by dvc94ch** [comment]
While I can find out by using static analysis what external variables the package is using, I have no way of determining which package provides them. Do build the package I need to know that. By prefetching I can analyse this. I could get this information from `packages.meteor.com` but that would not work when getting the packages from github.
Apart from that the meteor team is going to release a new roadmap very soon, and they are going to move away from prebuilding packages and move back to building packages from src.
Another problem is that core packages depending on other core packages don't have a constraint since:
> core package versions are locked through the release mechanism
This isn't a problem with up to date packages, since I can just fetch the latest version, but could become a challange to figure out, maybe manually as static configuration, which packages work together...
I updated the transformation example to show how I'm currently thinking of moving forward...

**Comment by guybedford** [comment]
@dvc94ch if we had a global Meteor object that was populated at runtime with the correct package globals as part of the wrapper (despite not being known at static analysis time), then we could assume they have been populated, as long as each wrapper contributes its part?

**Comment by dvc94ch** [comment]
Yes we can assume that. But then we can't use `import {Meteor} from 'meteor'`. Maybe it would work if we create a cjs module instead? But I quite like the es6 solution we've come up with so far... :)

**Comment by guybedford** [comment]
@dvc94ch this is why I had `packageFactory` etc before to generate the object live inside the wrapper.

**Comment by guybedford** [comment]
We can have a shared Meteor object that is populated, or we can have a wrapper that does dynamic population of this object based on knowing each module's exports to `Meteor`, which could be captured by the individual wrappers?

**Comment by dvc94ch** [comment]
I'm not understanding how this could solve the problem. For example:
I know a package depends on `['meteor', 'underscore']`.
I can figure out if I have to that a package uses `['Meteor', '_']` in it's code, but that those aren't defined inside the package.
Now I have to generate the `import` statements.
How do I know that `Meteor` comes from the package `meteor` and `_` comes from the package `underscore`?

**Comment by guybedford** [comment]
@dvc94ch perhaps we can rely on each wrapper exporting its exports as its module value:

```javascript
var coreExports = require('jspm-meteor/core-shim');
var underscoreExports = require('underscore');

module.exports = (function(Meteor) {
  // ... this module code
  // diff the Meteor global, minus coreExports, minus underscoreExports
  return diffedGlobal;
})(extend({}, coreExports, underscoreExports));
```

Alternatively we could just have a global `Meteor` object that we throw everything on to.

The shared code in the wrapper, like the extension and diffing processes can be turned into modules like:

```javascript
var wrapperFactory = require('jspm-meteor/wrapperFactory');
```

etc.

Let me know if that makes some sense?
